name: CI

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.14.0]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Restore node_modules from cache
      uses: actions/cache@v2
      with:
        path: |
          node_modules
          */*/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

    - name: Install dependencies
      run: yarn install --frozen-lockfile

    - name: Build
      run: yarn build

    - name: Run tests
      run: yarn test

  storybook:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.14.0]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Restore node_modules from cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      
      - name: Install dependencies
        run: yarn
      
      - name: Build Storybook
        run: yarn build-storybook --quiet
